import {FirstSubMenu, Menu, SecondSubMenu} from './menu';

export const MenuData:Menu[]=[new Menu('Home','pi pi-fw pi-home',
  [new FirstSubMenu('','',
    [new SecondSubMenu('','','')],
    '')],
  ''),
  new Menu('Admin','pi pi-fw pi-user',
    [new FirstSubMenu('','',
      [new SecondSubMenu('','','')],
      '')],
    ''),
  new Menu('My Accounts','pi pi-fw pi-plus',
    [new FirstSubMenu('','',
      [new SecondSubMenu('','','')],
      '')],
    ''),
  new Menu('FAQ','pi pi-fw pi-plus',
    [new FirstSubMenu('','',
      [new SecondSubMenu('','','')],
      '')],
    ''),
  new Menu('About us','pi pi-fw pi-plus',
    [new FirstSubMenu('','',
      [new SecondSubMenu('','','')],
      '')],
    ''),
  new Menu('Help','pi pi-fw pi-plus',
    [new FirstSubMenu('','',
      [new SecondSubMenu('','','')],
      '')],
    '')

]
